services:
  # Backend API Service
  - type: web
    name: nu3pbnb-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # You'll set this in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /
    
  # Frontend Service
  - type: web
    name: nu3pbnb-frontend
    env: static
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://nu3pbnb-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: nu3pbnb-mongodb
    databaseName: nu3pbnb 